# Generated by Django 5.2 on 2025-04-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('numero_colaborador', models.IntegerField()),
                ('setor', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='EpiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('numero_epi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_emprestimo', models.IntegerField()),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_prevista', models.DateField(blank=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField()),
                ('observacao', models.TextField(blank=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_app.colaboradormodel')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_app.epimodel')),
            ],
        ),
    ]
