# Generated by Django 5.2 on 2025-04-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='EpiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('n_serie', models.CharField()),
                ('status', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_retorno', models.DateField()),
                ('observacao', models.TextField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_app.colaboradormodel')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_app.epimodel')),
            ],
        ),
    ]
