# Generated by Django 5.2 on 2025-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradormodel',
            name='numero_colaborador',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='epimodel',
            name='numero_epi',
            field=models.IntegerField(),
        ),
    ]
