# Generated by Django 5.2 on 2025-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_app', '0002_alter_colaboradormodel_numero_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimomodel',
            name='numero_emprestimo',
            field=models.IntegerField(),
        ),
    ]
