# Generated by Django 5.2 on 2025-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_app', '0003_alter_emprestimomodel_numero_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimomodel',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimomodel',
            name='data_prevista',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimomodel',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
